version: '3.8'

include:
  - database/compose/database.yaml
  - database/compose/cache.yaml
  - cms/compose/directus.yaml
  - observability/compose/observability.yaml
  - utilities/compose/utility_tools.yaml

networks:
  cms_network:
    driver: bridge
