server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        refresh_interval: 5s
    relabel_configs:
      - source_labels: ['__meta_docker_container_name']
        regex: '/(.*)'
        target_label: 'container_name'
      - source_labels: ['__meta_docker_container_log_stream']
        target_label: 'stream'

  - job_name: container_logs
    pipeline_stages:
      - docker: {}
      - json:
          expressions:
            output: log
            stream: stream
            attrs: attrs
            tag: tag
      - timestamp:
          source: time
          format: RFC3339Nano
      - regex:
          expression: '(?P<container_id>(?P<container_name>.*)-[0-9a-f]{64})'
          source: container
      - regex:
          expression: '(?P<compose_service>[^_]+)_(?P<compose_container>[^_]+)(?:_(?P<container_number>\d+))?'
          source: container_name
      - labels:
          container_name:
          compose_service:
          compose_container:
          stream:
          tag:
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*.log

  - job_name: journal
    journal:
      max_age: 12h
      labels:
        job: systemd-journal
    relabel_configs:
      - source_labels: ['__journal__systemd_unit']
        target_label: 'unit'