# Main utilities compose file that includes all development tools
# Run with: docker compose up -d (from the utilities directory)

# Include individual service compose files
include:
  - ./compose/pgadmin.yaml
  - ./compose/mailhog.yaml

# Reference the external network (needed at this level too)
networks:
  cms_network:
    external: true
    name: cms_network
