# PgAdmin database management tool

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    # restart: unless-stopped
    ports:
      - "5050:80"
    volumes:
      - ../data/pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: "${PGADMIN_DEFAULT_EMAIL:-admin@example.com}"
      PGADMIN_DEFAULT_PASSWORD: "${PGADMIN_DEFAULT_PASSWORD:-pgadmin}"
    networks:
      - cms_network
    logging:
      <<: *default-logging
      options:
        max-size: "5m"
        max-file: "2"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=utility,container_name={{.Name}}"
