# Grafana visualization service

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    # restart: unless-stopped
    volumes:
      - ../data/grafana:/var/lib/grafana
      - ../config/grafana/provisioning:/etc/grafana/provisioning
      - ../config/grafana/dashboards:/etc/grafana/dashboards
    environment:
      GF_SECURITY_ADMIN_USER: "${GRAFANA_ADMIN_USER:-admin}"
      GF_SECURITY_ADMIN_PASSWORD: "${GRAFANA_ADMIN_PASSWORD:-grafana}"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_INSTALL_PLUGINS: "grafana-piechart-panel,grafana-clock-panel"
    ports:
      - "3000:3000"
    networks:
      - cms_network
    healthcheck:
      <<: *default-healthcheck-web
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:3000/login"]
    logging:
      <<: *default-logging
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=monitoring,container_name={{.Name}}"
