# Loki log aggregation service with Promtail log collector

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    # restart: unless-stopped
    volumes:
      - ../config/loki/loki-config.yaml:/etc/loki/loki-config.yaml
      - ../data/loki:/loki
    command: -config.file=/etc/loki/loki-config.yaml
    # ports:
    #   - "3100:3100"
    networks:
      - cms_network
    logging:
      <<: *default-logging
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=monitoring,container_name={{.Name}}"

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    # restart: unless-stopped
    volumes:
      - ../config/promtail/promtail-config.yaml:/etc/promtail/promtail-config.yaml
      - /var/log:/var/log
      - /var/lib/docker/containers:/var/lib/docker/containers
      - /var/run/docker.sock:/var/run/docker.sock
    command: -config.file=/etc/promtail/promtail-config.yaml
    ports:
      - "9080:9080"
    networks:
      - cms_network
    depends_on:
      - loki
    logging:
      <<: *default-logging
      options:
        max-size: "5m"
        max-file: "2"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=monitoring,container_name={{.Name}}"
