# Prometheus metrics collection service

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    # restart: unless-stopped
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - ../data/prometheus:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    ports:
      - "9090:9090"
    networks:
      - cms_network
    healthcheck:
      <<: *default-healthcheck-web
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:9090/-/healthy"]
    logging:
      <<: *default-logging
      options:
        max-size: "1m"
        max-file: "1"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=monitoring,container_name={{.Name}}"
