# Reusable logging configuration that can be included by other compose files

# Default JSON logging configuration with reasonable defaults
x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    labels: "service,environment"
    tag: "{{.Name}}"
    # Adding this ensures log messages are properly formatted as JSON
    env: "container_name={{.Name}},service={{.Service}}"
