# KeyDB cache service configuration

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    # restart: unless-stopped
    volumes:
      # Store data in the local data directory
      - ../data/keydb:/data
      # Mount configuration file
      - ../config/keydb/keydb.conf:/etc/keydb/keydb.conf
    command: keydb-server /etc/keydb/keydb.conf
    ports:
      - "6379:6379"
    networks:
      # Use the external network created by the root docker-compose
      - cms_network
    healthcheck:
      <<: *default-healthcheck-db
      test: ["CMD", "keydb-cli", "ping"]
    logging:
      <<: *default-logging
      options:
        max-size: "5m"
        max-file: "2"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=cache,container_name={{.Name}}"
