# Define reusable configurations
x-healthcheck-db: &default-healthcheck-db
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 10s

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    labels: "service,environment"
    tag: "{{.Name}}"
    env: "container_name={{.Name}},service={{.Service}}"

# KeyDB service configuration
services:
  keydb:
    image: eqalpha/keydb:latest
    container_name: keydb
    volumes:
      - ../data/keydb:/data
      - ../config/keydb/keydb.conf:/etc/keydb/keydb.conf
    command: keydb-server /etc/keydb/keydb.conf
    ports:
      - "6379:6379"
    networks:
      - cms_network
    healthcheck:
      <<: *default-healthcheck-db
      test: ["CMD", "keydb-cli", "ping"]
    logging:
      <<: *default-logging
      options:
        max-size: "5m"
        max-file: "2"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=cache,container_name={{.Name}}"