# Directus CMS service configuration

# Include common configuration
include:
  - ../../utils/logging.yml
  - ../../utils/healthchecks.yml

services:
  directus:
    image: directus/directus:11.5.1
    container_name: directus
    # restart: unless-stopped
    ports:
      - "8055:8055"
    volumes:
      # Store data in the local data directory
      - ../data/directus/uploads:/directus/uploads
      - ../data/directus/extensions:/directus/extensions
      - ../data/directus/config:/directus/config
    env_file:
      - ../config/directus/.env
    networks:
      # Use the external network created by the root docker-compose
      - cms_network
    healthcheck:
      <<: *default-healthcheck-web
      test: ["CMD", "wget", "--no-verbose", "--spider", "http://localhost:8055/server/health"]
    logging:
      <<: *default-logging
      options:
        max-size: "10m"
        max-file: "3"
        tag: "{{.Name}}"
        labels: "service,environment"
        env: "service=cms,container_name={{.Name}}"